In [2]:
from sklearn import model_selection
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np

dataset = pd.read_csv("../../../Life-Expectancy-Data.csv")

classCategories = np.asarray(dataset["Economy_status_Developed"])

print(dataset["Region"].unique())

['Middle East' 'European Union' 'Asia' 'South America'
 'Central America and Caribbean' 'Rest of Europe' 'Africa' 'Oceania'
 'North America']


In [8]:
# print all regions Economy_status_Developed 
print(dataset[["Region", "Economy_status_Developed"]])
# convert regions to one hot encoding
onehotencoder = OneHotEncoder()
onehotencoder.fit(dataset[["Region"]])
onehotencoded = onehotencoder.transform(dataset[["Region"]]).toarray()
print(onehotencoded)
dataset["Region"].corr(onehotencoded)

              Region  Economy_status_Developed
0        Middle East                         0
1     European Union                         1
2               Asia                         0
3      South America                         0
4        Middle East                         1
...              ...                       ...
2859          Africa                         0
2860            Asia                         0
2861            Asia                         0
2862  European Union                         1
2863  Rest of Europe                         1

[2864 rows x 2 columns]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


TypeError: unsupported type: <class 'numpy.ndarray'>